networks:
  blog:

volumes:
  db-data:

services:
  app:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - blog

  server:
    image: nginx:alpine
    ports:
      - ${SERVER_PORT:-80}:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - database
    networks:
      - blog

  database:
    image: mysql:8.4
    ports:
      - ${DB_FORWARD_PORT:-3306}:3306
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - blog
    